# Generated by Django 5.0.6 on 2024-05-23 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_geleria_usuario_galeria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='galeria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.galeria'),
        ),
    ]
