# Generated by Django 5.0.6 on 2024-05-23 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_usuario_galeria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='galeria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.galeria'),
        ),
    ]
