# Generated by Django 5.0.6 on 2024-05-24 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tema_delete_galeria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='imagens',
        ),
        migrations.AddField(
            model_name='imagem',
            name='tema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tema'),
        ),
        migrations.AddField(
            model_name='tema',
            name='titulo',
            field=models.TextField(null=True),
        ),
    ]
